FROM node:18.2.0-slim AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:latest

RUN chown -HR 1000:1000 /var/run && \
  chown -R 1000:1000 /var/cache/nginx && \
  sed -i '/^user/d' /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]